USE DATABASE AGENTGRAVITY;

--------------------------------------------------
-- PRIMARY KEYS
--------------------------------------------------

ALTER TABLE BUSINESS.KPI_METRICS
ADD CONSTRAINT PK_KPI
PRIMARY KEY (KPI_ID);

ALTER TABLE INCIDENTS.INCIDENTS
ADD CONSTRAINT PK_INCIDENT
PRIMARY KEY (INCIDENT_ID);

ALTER TABLE INCIDENTS.ROOT_CAUSES
ADD CONSTRAINT PK_ROOTCAUSE
PRIMARY KEY (ROOT_CAUSE_ID);

ALTER TABLE INCIDENTS.RECOVERY_ACTIONS
ADD CONSTRAINT PK_ACTION
PRIMARY KEY (ACTION_ID);

ALTER TABLE INCIDENTS.IMPACT_ANALYSIS
ADD CONSTRAINT PK_IMPACT
PRIMARY KEY (IMPACT_ID);

ALTER TABLE INCIDENTS.EXECUTIVE_REPORTS
ADD CONSTRAINT PK_REPORT
PRIMARY KEY (REPORT_ID);

ALTER TABLE SECURITY.AGENT_AUDIT_LOG
ADD CONSTRAINT PK_LOG
PRIMARY KEY (LOG_ID);

--------------------------------------------------
-- FOREIGN KEYS
--------------------------------------------------

ALTER TABLE INCIDENTS.INCIDENTS
ADD CONSTRAINT FK_INCIDENT_KPI
FOREIGN KEY (KPI_ID)
REFERENCES BUSINESS.KPI_METRICS(KPI_ID);

ALTER TABLE INCIDENTS.ROOT_CAUSES
ADD CONSTRAINT FK_ROOTCAUSE_INCIDENT
FOREIGN KEY (INCIDENT_ID)
REFERENCES INCIDENTS.INCIDENTS(INCIDENT_ID);

ALTER TABLE INCIDENTS.RECOVERY_ACTIONS
ADD CONSTRAINT FK_ACTION_INCIDENT
FOREIGN KEY (INCIDENT_ID)
REFERENCES INCIDENTS.INCIDENTS(INCIDENT_ID);

ALTER TABLE INCIDENTS.IMPACT_ANALYSIS
ADD CONSTRAINT FK_IMPACT_INCIDENT
FOREIGN KEY (INCIDENT_ID)
REFERENCES INCIDENTS.INCIDENTS(INCIDENT_ID);

ALTER TABLE INCIDENTS.EXECUTIVE_REPORTS
ADD CONSTRAINT FK_REPORT_INCIDENT
FOREIGN KEY (INCIDENT_ID)
REFERENCES INCIDENTS.INCIDENTS(INCIDENT_ID);