CREATE OR REPLACE TABLE AGENTGRAVITY.INCIDENTS.RECOVERY_PLAN
(
    PLAN_ID INTEGER AUTOINCREMENT,

    GENERATED_AT TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP,

    EXECUTIVE_SUMMARY STRING,

    IMMEDIATE_ACTIONS STRING,

    SHORT_TERM_ACTIONS STRING,

    LONG_TERM_ACTIONS STRING,

    EXPECTED_BUSINESS_OUTCOME STRING,

    SUCCESS_METRICS STRING,

    RISK_LEVEL STRING
);